# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 619977ad866b9804841d8e9a871445d624cc92c98efdb6fbf37c279b785405e845d4847d28c03ea8ac3c26402e3cf545fe29d83c622b518f1d404c27a2690ca0

test:
  secret_key_base: 2012654511614a5eb75ba275591627c7a58f699adc4c41961f94ff9a24727b5185314feb516ef74bf4e387d4699532da8cf7eb38807dfc777416f77f6317993a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
